spring:
  application:
    name: ELH-core-service-registry
  cloud:
    inetutils:
      preferred-networks: 127.0.0.1
server:
  port: 8081

app:
  config:
    keycloak:
      url: http://localhost:8080
      realm: tcnw-elearn

eureka:
  server:
    peer-node-read-timeout-ms: 5000
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    fetch-registry: false
    register-with-eureka: false

